server:
  port: 3344
spring:
  application:
    name: cloud-config-center # 注册在eureka服务器的名字
  cloud:
    config:
      server:
        git:
          uri:  # github配置中心地址
          search-paths:  # 搜索目录
      # 读取分支
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
