server:
  port: 80


#eureka配置信息
eureka:
  client:
    # 表示是否将自己注册到eurekaServer 默认为true
    register-with-eureka: true
    # 是否从eurekaServer抓取已有的注册信息,默认为true.单节点无所谓,集群必须设为true才能使用ribbon负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
  application:
    name: cloud-consumer-feign-order

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000